name: Enforce Release PR Checklist

on:
  pull_request:
    branches:
      - production

jobs:
  checklist:
    name: Enforce Release PR Checklist
    if: github.event.pull_request.base.ref == 'production'
    runs-on: ubuntu-latest
    steps:
      - name: Validate checklist completion (with bypass label)
        run: |
          echo "Checking PR body and labels..."
          BODY=$(jq -r .pull_request.body "$GITHUB_EVENT_PATH")
          echo "$BODY" > pr_body.txt

          HAS_BYPASS=$(jq -r '.pull_request.labels[]?.name' "$GITHUB_EVENT_PATH" | grep -x 'skip-checklist' || true)
          if [ -n "$HAS_BYPASS" ]; then
            echo "🟡 Bypass active: label 'skip-checklist' present. Skipping checklist enforcement."
            exit 0
          fi

          if grep -q "\\- \\[ \\]" pr_body.txt; then
            echo "❌ Some checklist items are not completed."
            echo "Please ensure all required items are checked ([x]) or apply the 'skip-checklist' label with justification."
            exit 1
          else
            echo "✅ All checklist items completed."
          fi
